const additionalHeaders = [
   // WARNING!These values are positionally dependent; only add to the bottom
   "ID", //hash of 'AssetLabel' and'UploadTime' (not UploadFBTime)
   "FName", //filename
   "UploadFBTime", // time when file is uploaded to firebase
   "State", // state where chair is deployed;
   "Beach", // beach where chair is deployed
   "RentalAgent", // rental agent where chair is deployed
];

export const mandatoryHeaders = [
   "AssetLabel",
   "Beach",
   "Fname",
   "ID",
   "Latitude",
   "Longitude",
   "RentalAgent",
   "State",
   "UpdateTime",
   "UploadFBTime",
];

export const statesArray = [
   "Alabama",
   "Alaska",
   "American Samoa",
   "Arizona",
   "Arkansas",
   "California",
   "Colorado",
   "Connecticut",
   "Delaware",
   "District of Columbia",
   "Florida",
   "Georgia",
   "Guam",
   "Hawaii",
   "Idaho",
   "Illinois",
   "Indiana",
   "Iowa",
   "Kansas",
   "Kentucky",
   "Louisiana",
   "Maine",
   "Maryland",
   "Massachusetts",
   "Michigan",
   "Minnesota",
   "Minor Outlying Islands",
   "Mississippi",
   "Missouri",
   "Montana",
   "Nebraska",
   "Nevada",
   "New Hampshire",
   "New Jersey",
   "New Mexico",
   "New York",
   "North Carolina",
   "North Dakota",
   "Northern Mariana Islands",
   "Ohio",
   "Oklahoma",
   "Oregon",
   "Pennsylvania",
   "Puerto Rico",
   "Rhode Island",
   "South Carolina",
   "South Dakota",
   "Tennessee",
   "Texas",
   "U.S. Virgin Islands",
   "Utah",
   "Vermont",
   "Virginia",
   "Washington",
   "West Virginia",
   "Wisconsin",
   "Wyoming",
];

export const beachesArray = [
   "Ocean City, MD",
   "Assateague",
   "Ocean City, NJ",
   "Cape May",
   "Avalon",
   "Wildwood",
   "Stone Harbor",
   "Sea Isle City",
   "Long Beach Island",
   "Atlantic City",
   "Seaside Heights",
   "Virginia Beach",
   "OBX",
   "Sunset Beach",
   "Ocean Isle Beach",
   "Holden Beach",
   "Wilmington",
   "Southport",
   "North Myrtle Beach",
   "Myrtle Beach",
   "Bethany",
   "Rehoboth",
   "Fenwick",
   "Dewey",
   "Boca Raton",
   "Boynton Beach",
   "Clearwater",
   "Cocoa Beach",
   "Deerfield Beach",
   "Delray Beach",
   "Fort Lauderdale",
   "Golden Beach",
   "Highland Beach",
   "Hollywood Beach",
   "Indian Harbour Beach",
   "Indian Rocks",
   "Indian Shores",
   "Madeira Beach",
   "Melbourne Beach",
   "Miami Beach",
   "Naples",
   "Pompano Beach",
   "Port Canaveral",
   "Redington Beach",
   "Satellite Beach",
   "St. Pete Beach",
   "Sunny Isle",
   "Tierra Verde",
   "Treasure Island",
   "West Palm Beach",
];

export const rentalAgentArray = [
   "SANDHELPER",
   "STONE HARBOR CRIB & BEACH RENTAL",
   "BEACH EASY RENTALS",
   "BEACH POWER MOBILITY",
   "JUST FOR BEACH RENTALS",
   "MAC BROS. BEACH SETUPS",
   "JULIE'S RENTALS",
   "COASTAL GOLF CART RENTALS",
   "MOBILITY CENTER OF THE GRAND STRAND",
];

export default additionalHeaders;
